name: MLflow Training dan Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  #Izin buat upload artifact

    steps:
    #Ambil kodingan
    - name: Checkout code
      uses: actions/checkout@v3

    #Siapkan Python
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    #Install Library
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow scikit-learn pandas numpy matplotlib seaborn

    #Jalankan Training
    - name: Run MLflow Project
      run: |
        cd MLProject
        mlflow run . --env-manager=local --experiment-name "CI_Run_jhr"

    #Upload Hasil Model
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/mlruns/
        retention-days: 5

    #Login ke Docker
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/msmlproject-juhar:latest ./MLProject
        docker push ${{ secrets.DOCKER_USERNAME }}/msmlproject-juhar:latest
